/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    EditProgressDialog: typeof import('./src/components/report/EditProgressDialog.vue')['default']
    EditTypeDialog: typeof import('./src/components/report/EditTypeDialog.vue')['default']
    RegulatorFormDialog: typeof import('./src/components/regulator/RegulatorFormDialog.vue')['default']
    RejectDialog: typeof import('./src/components/report/RejectDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
