export const PERMISSION_NAME = {
  DASHBOARD: 'DASHBOARD',
  CRUD: 'CRUD',
  USERS: 'USERS',
  ROLES: 'ROLES',
  PERMISSIONS: 'PERMISSIONS',
  REGULATORS: 'REGULATORS',
  STATUSES: 'STATUSES',
  REPORTS: 'REPORTS',
  REPORTS_APPROVAL: 'REPORTS_APPROVAL',
}
