export const PERMISSION_NAME = {
  DASHBOARD: 'DASHBOARD',
  USERS: 'USERS',
  ROLES: 'ROLES',
  PERMISSIONS: 'PERMISSIONS',
  REGULATORS: 'REGULATORS',
  STATUSES: 'STATUSES',
  REPORTS: 'REPORTS',
}
