export const REPORT_TYPE_ID = {
  DRAFT: 1,
  PRIMARY: 2,
  AUDIT: 3,
  REQUEST_REVIEW: 4,
  APPROVED: 5,
  REJECTED: 6,
}

export const REPORT_TYPE_CODE = {
  DRAFT: 'draft',
  PRIMARY: 'primary',
  AUDIT: 'audit',
  REQUEST_REVIEW: 'request-review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
}

export const REPORT_TYPE_NAME = {
  [REPORT_TYPE_ID.DRAFT]: REPORT_TYPE_CODE.DRAFT,
  [REPORT_TYPE_ID.PRIMARY]: REPORT_TYPE_CODE.PRIMARY,
  [REPORT_TYPE_ID.AUDIT]: REPORT_TYPE_CODE.AUDIT,
  [REPORT_TYPE_ID.REQUEST_REVIEW]: REPORT_TYPE_CODE.REQUEST_REVIEW,
  [REPORT_TYPE_ID.APPROVED]: REPORT_TYPE_CODE.APPROVED,
  [REPORT_TYPE_ID.REJECTED]: REPORT_TYPE_CODE.REJECTED,
}

export const REPORT_TYPE_TITLE = {
  [REPORT_TYPE_CODE.DRAFT]: 'report.draft',
  [REPORT_TYPE_CODE.PRIMARY]: 'report.primary',
  [REPORT_TYPE_CODE.AUDIT]: 'report.audit',
  [REPORT_TYPE_CODE.REQUEST_REVIEW]: 'app.nav.requestReview',
  [REPORT_TYPE_CODE.APPROVED]: 'app.nav.approved',
  [REPORT_TYPE_CODE.REJECTED]: 'app.nav.rejected',
}

export const REPORT_TYPE_OPTIONS = [
  { title: REPORT_TYPE_TITLE[REPORT_TYPE_CODE.DRAFT], value: REPORT_TYPE_ID.DRAFT },
  { title: REPORT_TYPE_TITLE[REPORT_TYPE_CODE.PRIMARY], value: REPORT_TYPE_ID.PRIMARY },
  { title: REPORT_TYPE_TITLE[REPORT_TYPE_CODE.AUDIT], value: REPORT_TYPE_ID.AUDIT },
]
